#!/bin/bash

# Script per eseguire il sistema nativamente con Real-Time
# Richiede 4 terminali separati

echo "=== gRPC Orchestrator - Native Real-Time Execution ==="
echo ""
echo "Questo script mostra i comandi da eseguire in 4 terminali separati."
echo "Copia e incolla ogni comando nel terminale corrispondente."
echo ""
echo "IMPORTANTE: Esegui i comandi con 'sudo' per abilitare real-time!"
echo ""
echo "========================================="
echo "TERMINALE 1 - Orchestrator:"
echo "========================================="
echo "cd /home/vboxuser/projects/grpc_orchestrator/build"
echo "sudo ./bin/orchestrator_main \\"
echo "  --address 0.0.0.0:50050 \\"
echo "  --policy fifo \\"
echo "  --priority 80 \\"
echo "  --cpu-affinity 0 \\"
echo "  --lock-memory"
echo ""
echo "========================================="
echo "TERMINALE 2 - Task 1:"
echo "========================================="
echo "cd /home/vboxuser/projects/grpc_orchestrator/build"
echo "sudo ./bin/task_main \\"
echo "  --name task_1 \\"
echo "  --address localhost:50051 \\"
echo "  --orchestrator localhost:50050 \\"
echo "  --policy fifo \\"
echo "  --priority 75 \\"
echo "  --cpu-affinity 1 \\"
echo "  --lock-memory"
echo ""
echo "========================================="
echo "TERMINALE 3 - Task 2:"
echo "========================================="
echo "cd /home/vboxuser/projects/grpc_orchestrator/build"
echo "sudo ./bin/task_main \\"
echo "  --name task_2 \\"
echo "  --address localhost:50052 \\"
echo "  --orchestrator localhost:50050 \\"
echo "  --policy fifo \\"
echo "  --priority 75 \\"
echo "  --cpu-affinity 2 \\"
echo "  --lock-memory"
echo ""
echo "========================================="
echo "TERMINALE 4 - Task 3:"
echo "========================================="
echo "cd /home/vboxuser/projects/grpc_orchestrator/build"
echo "sudo ./bin/task_main \\"
echo "  --name task_3 \\"
echo "  --address localhost:50053 \\"
echo "  --orchestrator localhost:50050 \\"
echo "  --policy fifo \\"
echo "  --priority 75 \\"
echo "  --cpu-affinity 3 \\"
echo "  --lock-memory"
echo ""
echo "========================================="
echo "ORDINE DI ESECUZIONE:"
echo "========================================="
echo "1. Avvia TERMINALE 1 (Orchestrator)"
echo "2. Avvia TERMINALE 2, 3, 4 (Tasks) in qualsiasi ordine"
echo "3. Osserva i log per vedere l'esecuzione real-time!"
echo ""
echo "Per fermare: Premi Ctrl+C in ogni terminale"
echo ""
echo "========================================="
echo "VERIFICA REAL-TIME:"
echo "========================================="
echo "Dopo aver avviato, in un 5° terminale esegui:"
echo ""
echo "# Verifica policy RT dell'orchestrator:"
echo "sudo chrt -p \$(pgrep orchestrator_main)"
echo ""
echo "# Verifica policy RT dei task:"
echo "sudo chrt -p \$(pgrep task_main)"
echo ""
echo "# Monitora con htop:"
echo "htop"
echo ""
echo "Dovresti vedere priorità RT (FIFO) e jitter molto basso!"
echo "========================================="
